# Generated by Django 4.1 on 2022-08-06 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=200)),
                ('income', models.IntegerField(default=0)),
                ('rides', models.IntegerField(default=0)),
                ('fuel', models.IntegerField(default=0)),
                ('wash', models.IntegerField(default=0)),
                ('fix', models.IntegerField(default=0)),
                ('service', models.IntegerField(default=0)),
                ('other', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('salary', models.IntegerField(default=0)),
                ('tips', models.IntegerField(default=0)),
                ('costs', models.IntegerField(default=0)),
                ('owns', models.IntegerField(default=0)),
                ('fines', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('cash', models.BooleanField(default=False)),
                ('toll', models.IntegerField(default=0)),
                ('save_tax', models.BooleanField(default=False)),
                ('extra_tax', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True, max_length=200)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_ride.car')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_ride.driver')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_ride.shift')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_ride.shift'),
        ),
    ]
