# Generated by Django 4.1 on 2022-08-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ride', '0002_rename_owns_driver_deposit_remove_car_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
