# Generated by Django 4.1 on 2022-08-13 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_ride', '0005_alter_ride_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tax', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='ride',
            name='extra_tax',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='my_ride.extratax'),
        ),
    ]
