# Generated by Django 4.1 on 2022-08-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ride', '0008_ride_saved_tax_result_alter_ride_extra_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
