# Generated by Django 4.1 on 2022-08-29 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_ride', '0010_alter_shift_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miles_s', models.IntegerField(default=0)),
                ('miles_f', models.IntegerField(default=0)),
                ('hours', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=0)),
                ('wash', models.IntegerField(default=0)),
                ('water', models.IntegerField(default=0)),
                ('other', models.IntegerField(default=0)),
                ('tolls', models.IntegerField(default=0)),
                ('income', models.IntegerField(default=0)),
                ('cash', models.IntegerField(default=0)),
                ('tips', models.IntegerField(default=0)),
                ('s_tax', models.IntegerField(default=0)),
                ('x_tax', models.IntegerField(default=0)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_ride.car')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_ride.shift')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_ride.driver')),
            ],
        ),
    ]
