# Generated by Django 4.1 on 2022-09-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ride', '0013_balancedriver_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='number',
            field=models.CharField(max_length=50),
        ),
    ]
