# Generated by Django 4.1 on 2022-09-06 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_ride', '0014_alter_ride_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancedriver',
            name='fuel',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BalanceCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_fuel', models.IntegerField(default=0)),
                ('c_wash', models.IntegerField(default=0)),
                ('c_toll', models.IntegerField(default=0)),
                ('c_fine', models.IntegerField(default=0)),
                ('c_service', models.IntegerField(default=0)),
                ('c_repair', models.IntegerField(default=0)),
                ('c_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_ride.car')),
                ('c_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_ride.shift')),
                ('c_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_ride.driver')),
                ('c_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_ride.balancedriver')),
            ],
        ),
    ]
