# Generated by Django 4.1 on 2022-09-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ride', '0015_balancedriver_fuel_balancecar'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancedriver',
            name='buy_s',
            field=models.IntegerField(default=0),
        ),
    ]
