# Generated by Django 4.1 on 2022-09-16 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_ride', '0016_balancedriver_buy_s'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_ride.car')),
                ('plan_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_ride.shift')),
                ('plan_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_ride.driver')),
            ],
        ),
    ]
