# Generated by Django 4.1 on 2022-09-16 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_ride', '0017_planshift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planshift',
            name='plan_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_ride.car', unique=True),
        ),
    ]
