# Generated by Django 4.1 on 2022-09-19 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_ride', '0019_alter_planshift_plan_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancedriver',
            name='buy_s',
            field=models.IntegerField(default=0, verbose_name='Покупка смены'),
        ),
        migrations.AlterField(
            model_name='balancedriver',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_ride.car', verbose_name='Авто'),
        ),
        migrations.AlterField(
            model_name='balancedriver',
            name='cash',
            field=models.IntegerField(default=0, verbose_name='Наличные'),
        ),
        migrations.AlterField(
            model_name='balancedriver',
            name='comment',
            field=models.CharField(blank=True, max_length=300, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='balancedriver',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_ride.shift', verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='balancedriver',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_ride.driver', verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='balancedriver',
            name='fuel',
            field=models.IntegerField(default=0, verbose_name='Топливо'),
        ),
        migrations.AlterField(
            model_name='balancedriver',
            name='hours',
            field=models.IntegerField(default=0, verbose_name='Часы на линии'),
        ),
        migrations.AlterField(
            model_name='balancedriver',
            name='income',
            field=models.IntegerField(default=0, verbose_name='Выручка'),
        ),
        migrations.AlterField(
            model_name='balancedriver',
            name='mileage',
            field=models.IntegerField(default=0, verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='balancedriver',
            name='miles_f',
            field=models.IntegerField(default=0, verbose_name='Пробег в конце смены'),
        ),
        migrations.AlterField(
            model_name='balancedriver',
            name='miles_s',
            field=models.IntegerField(default=0, verbose_name='Пробег в начале смены'),
        ),
        migrations.AlterField(
            model_name='balancedriver',
            name='other',
            field=models.IntegerField(default=0, verbose_name='Прочее'),
        ),
        migrations.AlterField(
            model_name='balancedriver',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Приоритет +'),
        ),
        migrations.AlterField(
            model_name='balancedriver',
            name='s_tax',
            field=models.IntegerField(default=0, verbose_name='Съэкономленная комиссия'),
        ),
        migrations.AlterField(
            model_name='balancedriver',
            name='tips',
            field=models.IntegerField(default=0, verbose_name='Чаевые б/н'),
        ),
        migrations.AlterField(
            model_name='balancedriver',
            name='tolls',
            field=models.IntegerField(default=0, verbose_name='ЗСД'),
        ),
        migrations.AlterField(
            model_name='balancedriver',
            name='wash',
            field=models.IntegerField(default=0, verbose_name='Мойка'),
        ),
        migrations.AlterField(
            model_name='balancedriver',
            name='water',
            field=models.IntegerField(default=0, verbose_name='Вода'),
        ),
        migrations.AlterField(
            model_name='balancedriver',
            name='x_tax',
            field=models.IntegerField(default=0, verbose_name='Сумма доп.комиссий'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_ride.car', verbose_name='Авто'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='cash',
            field=models.BooleanField(default=False, verbose_name='За наличные'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='comment',
            field=models.TextField(blank=True, max_length=200, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_ride.driver', verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='extra_tax',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_ride.extratax', verbose_name='Режим доп.комиссии'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='number',
            field=models.CharField(max_length=50, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='save_tax',
            field=models.BooleanField(default=False, verbose_name='С покупкой смены'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='saved_tax_result',
            field=models.IntegerField(default=0, verbose_name='Экономия комиссии'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_ride.shift', verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='tax_result',
            field=models.IntegerField(default=0, verbose_name='Сумма доп.комиссии'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='tip',
            field=models.IntegerField(default=0, verbose_name='Чаевые'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='toll',
            field=models.IntegerField(default=0, verbose_name='ЗСД'),
        ),
    ]
